#!/bin/bash

# Install and clone git repo
yum install git -y
git clone https://github.com/jkelso662/mirror.git

# Install AWS cli
curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
unzip awscliv2.zip
./aws/install

# Install inotify-tools for s3sync.sh
amazon-linux-extras install epel -y
yum update -y
yum install inotify-tools -y

# Setup mirror dirs and dependencies
cd mirror/
mkdir output/
mkdir output/clone/
mkdir output/crawl/
mkdir output/search/
mkdir output/snippets/
python3 -m setup.py install

echo "Remember to export your dev vars"
